## Index

- tensorflow loading
- numpy data initialization with random function
- saving the array with savez with extension .npz
- loading back the .npz file
- deep learning layers
- optimizers
- loss functions
- preditions from model
- finding the weights and biases

In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.3.1'

In [5]:

import numpy as np

In [6]:
# Tensor is multidimennsional array 
# scalar -> vector -> Tensor

In [10]:
n = 1000
x = np.random.uniform(-10,10,(n,1))
y = np.random.uniform(-10,10,(n,1))

inputs = np.column_stack((x,y))

noise = np.random.uniform(-1,1,(n,1))

# f = 45x -78y + 23 + noise
targets = 45*x - 78*y + 23 + noise



In [13]:
targets.shape

(1000, 1)

In [15]:
np.savez('tensor',inputs1 = inputs , targets1 = targets )

In [16]:
# solving the Tensorflow


In [17]:
data = np.load('tensor.npz')

In [18]:
data

In [19]:
input_var = 2
output_var = 1

In [24]:
data['inputs1'].shape , data['targets1'].shape

((1000, 2), (1000, 1))

In [23]:
model = tf.keras.Sequential([
                                tf.keras.layers.Dense(output_var)
                            ])

model.compile(optimizer='sgd', loss = 'mean_squared_error' )

model.fit(data['inputs1'], data['targets1'], epochs = 100, verbose =0)

### EPOCH = iteration over the full dataset

### Extract the weight and bias from trained model

In [47]:
model.layers[0].get_weights()                               
                                

[array([[ 45.00284],
        [-78.02696]], dtype=float32),
 array([23.00198], dtype=float32)]

In [48]:
weights = model.layers[0].get_weights()[0]
biases = model.layers[0].get_weights()[1]

## Extract the outputs ( make predictions)

In [50]:
# new data to test the model
test_input = np.array([[2,3],[20,30]])


In [51]:
# directly calculating the test_output from equation
# f = 45x -78y + 23 + noise

test_output = np.dot(test_input,np.array([[45],[-78]])) + 23
test_output

array([[ -121],
       [-1417]])

In [53]:
# calculating the output from model 
model.predict_on_batch(test_input)

array([[ -121.07323],
       [-1417.7501 ]], dtype=float32)

### both result are same, which validates the model.
# Great !!

### now will slowly go deeper in Deep learning concepts

In [61]:
# kernal_initializer and bias_initializer can be provided in model.
# which is to provide the range to weight and bias. eg. (-1 to 1)
# kernal is the another name to weight.

# Learning rate : to be added in model

In [102]:
model = tf.keras.Sequential([
                                tf.keras.layers.Dense(output_var, 
                                                      kernel_initializer = tf.random_uniform_initializer(minval=-0.1,maxval = 0.1),
                                                      bias_initializer = tf.random_uniform_initializer(minval=-0.1,maxval = 0.1))
                            ])

custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.01)

model.compile(optimizer=custom_optimizer, loss = 'MeanSquaredError' )

model.fit(data['inputs1'], data['targets1'], epochs = 40, verbose =0)

In [103]:
model.layers[0].get_weights()

[array([[ 44.961323],
        [-78.03553 ]], dtype=float32),
 array([22.998302], dtype=float32)]