In [1]:
import torch 

In [2]:
%config Completer.use_jedi = False

In [3]:
torch.__version__

'1.1.0'

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3,4])

In [7]:
torch.as_tensor(x)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [8]:
z= torch.from_numpy(x)

In [9]:
y = [1,2,4,5]

In [10]:
torch.as_tensor(y).dtype

torch.int64

In [11]:
z.dtype

torch.int32

In [12]:
x, z

(array([1, 2, 3, 4]), tensor([1, 2, 3, 4], dtype=torch.int32))

In [13]:
x[0]=100

In [14]:
z

tensor([100,   2,   3,   4], dtype=torch.int32)

In [17]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [33]:
x = torch.tensor(2.,requires_grad=True)

In [34]:
x

tensor(2., requires_grad=True)

In [35]:
y = 2*x**3 + x**2 + 4*x +3

In [36]:
y

tensor(31., grad_fn=<AddBackward0>)

In [38]:
y.backward()

In [39]:
x.grad

tensor(32.)

In [40]:
# on new data (matrix)

In [173]:
x = torch.tensor([[1.,2.,4.],[1,2,3]],requires_grad=True)

In [174]:
# first layer
y = x**2 + x + 1

In [175]:
y

tensor([[ 3.,  7., 21.],
        [ 3.,  7., 13.]], grad_fn=<AddBackward0>)

In [176]:
# second layer
z = y**2

In [177]:
z

tensor([[  9.,  49., 441.],
        [  9.,  49., 169.]], grad_fn=<PowBackward0>)

In [178]:
# outout layer
out = z.sum()

In [179]:
out

tensor(726., grad_fn=<SumBackward0>)

In [180]:
out.backward()

In [181]:
x.grad

tensor([[ 18.,  70., 378.],
        [ 18.,  70., 182.]])

In [168]:
# now analyse the data at each layer.
# out = sum of all ((x**2 + x + 1)**2)
# derivative of out with respect of x is = 2*(x**2 + x + 1)*(2*x+1)
# now put first value which is 1, answer would be = 2*(1+1+1)*(2+1) = 18
# now put first value which is 2, answer would be = 2*(4+2+1)*(4+1) = 70
# now put first value which is 3, answer would be = 2*(16+4+1)*(8+1) = 182
# now put first value which is 4, answer would be = 2*(16+4+1)*(8+1) = 378


# if mean is there --> then need to take mean , divide the values with total elements in matrix. 

In [182]:
# with mean

x = torch.tensor([[1.,2.,4.],[1,2,3]],requires_grad=True)
# first layer
y = x**2 + x + 1
# second layer
z = y**2
# outout layer
out = z.mean()

out.backward()
x.grad

tensor([[ 3.0000, 11.6667, 63.0000],
        [ 3.0000, 11.6667, 30.3333]])

In [183]:
# with max

x = torch.tensor([[1.,2.,4.],[1,2,3]],requires_grad=True)
# first layer
y = x**2 + x + 1
# second layer
z = y**2
# outout layer
out = z.max()

out.backward()
x.grad

tensor([[  0.,   0., 378.],
        [  0.,   0.,   0.]])

In [184]:
# with sum

x = torch.tensor([[1.,2.,4.],[1,2,3]],requires_grad=True)
# first layer
y = x**2 + x + 1
# second layer
z = y**2
# outout layer
out = z.sum()

out.backward()
x.grad

tensor([[ 18.,  70., 378.],
        [ 18.,  70., 182.]])