In [1]:
import torch 

In [2]:
%config Completer.use_jedi = False

In [3]:
torch.__version__

'1.1.0'

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
x = np.array([1,2,3,4])

In [7]:
torch.as_tensor(x)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [12]:
z= torch.from_numpy(x)

In [9]:
y = [1,2,4,5]

In [21]:
torch.as_tensor(y).dtype

torch.int64

In [20]:
z.dtype

torch.int32

In [36]:
x, z

(array([1, 2, 3, 4]), tensor([1, 2, 3, 4], dtype=torch.int32))

In [38]:
x[0]=100

In [39]:
z

tensor([100,   2,   3,   4], dtype=torch.int32)